matrix:
  include:
    - os: windows
      env: 
        - BUILD_TARGET=win32 
      language: cpp
      python: "2.7"

before_install:
  - choco install python2
  - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
  - travis-scripts/before-install.sh

script:
  - travis-scripts/run-script.sh
